sudo: required    
language: go    
go:    
- '1.11'
services:    
- docker    
env:    
  global:    
  - secure: VPl3TGj9cNWdsOIpvUHva1cp8gjlzL2T2ZASlf2RLpFnHn8ggCRhFc9QkSLxz6wLv155nCeLCkW3Pp7OZOXH9Q4EZDX3kBzuQisDaUNuzpaXz0w9XWE5U/SW4uGGpN2p1EZH61FW0Mi2o+vHp79gS+cdfa2fnNy1uz+4u57Ij3HbQeN28vETe9QNHu9VhS7vHMqOEBUTEaXTZGUgZ56bA9uQfudYZymN+EFPrWjGrMGNSnzEPoNq8yEoEqsGbZbdaKXWP9RCdcM4huWytme3EN775jWzt8TTPtPbNQJKiD1tiDToz0dCCvn0i4G/cuJa3NgBSi08f3JfC2ekKKTzpWdtoh8nsLvnPw1lpMZzNoTXY4yHffraat7i9kxaXa45PzM5w8t0HWzaMgY0IU3hVA6ot2eu9r8h7d77KvedluWHqjq7ATCr6QzWWMZAd7GVOmM/j10usOeKHZlvQtUsBCoghKN78qAqJdfPwtPQqsJ4RY42XPoQjRVAwzhTzTWsfdryDim+120wrDKBp5k8/6ugJMebz1PM1U1BjTvNN4RLCkimkjWRkKzZRId3mcsa9e5vke6wkXg/swRge0X4Wtdlxp2N7cIkuKy2F3LA5U8b+qvDwn/SzGPo5DAILQchC4bm1VIdxF7h305F/dtqdSpCoj9rkNKI+kGVLF27a0k=
  - secure: DEg+zxj3dVyK/iT42tUO1IjctDUJ67ts3XKSGDRE7xOd5K6anIVjb4kf3OIuhB3UOGYJnRmpo3y74Tml1S5dTFcu2hYCf7+KMv9Tzwzp7SDZ2P7Y9S8iA0fdz+gCI8dsNEoRBKVYtWktq+D3SZxPit+Tw3QxA+XubrV1CSlf++SCOYrjSahA75BCdMer+g2BL382zB0y4rvdQ+qTYAk37BdyyA55P2XjcwhrzyclDcSf+ZtVYYIl8mIqvDNBCMeFz7dy6UJrF6NYcwTUybl7IrL2CzAgQDrFwgmb72kqqYbrnWUG9TVY9UPY0D6/fM9kZMc4tk7y9q8E67cLE3lHp3aOluI22OjWyAX+oekkUVv3mC0MbuXlDn75bhDIHSXzlsycwfOX8f9b0o3K1HtU9SrfkCx9HfLBOeF6GJcGDPLBhq3l1kf/pO+O+ruAU21jzIQkx8QFfwQMIhVMMFObb86CF5JiapfMCh2Cbo5ztwNj/IVduCRO6AILJc9NwV7vojcs+xB8exB0W2Fk8r+HIAfE8Q76qgu5IHGDrQsWb8Kb62AU2pkOh8ToaTd9elK7QFgxLO66ctduAuGfbfUk2JhsLhaBYUZNPAYBKTCMVdA3NTS6pn/Dh+++0osxdTc18ulreo4Uzks+fgWwdw0j21dt8XS3p8r137a1avSyMqw=
  - KUBERNETES_CONFIG=${HOME}/.kube/config    
  - GO111MODULE=on
  matrix:    
  - CHANGE_MINIKUBE_NONE_USER=true   
jobs:
  include:
  - stage: lint
    script:
    - make linters
  - stage: build and test
    script:
    - go mod download
    - ./.travis/prepare-environment.sh
    - make test
    - make
stages:
  - lint
  - build and test
after_success:
- echo 'Build succeeded'
after_failure:
- echo 'Build failed'
