apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresqls.postgresql.openshift.com
spec:
  group: postgresql.openshift.com
  names:
    kind: PostgreSQL
    listKind: PostgreSQLList
    plural: postgresqls
    singular: postgresql
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            managementState:
              type: string
            nodes:
              additionalProperties:
                properties:
                  image:
                    type: string
                  priority:
                    format: int64
                    type: integer
                  resources:
                    type: object
                  storage:
                    properties:
                      size:
                        type: string
                      storageClassName:
                        type: string
                    type: object
                required:
                - priority
                - storage
                type: object
              type: object
          required:
          - managementState
          - nodes
          type: object
        status:
          properties:
            nodes:
              additionalProperties:
                properties:
                  deploymentName:
                    type: string
                  pgversion:
                    type: string
                  priority:
                    format: int64
                    type: integer
                  role:
                    type: string
                  serviceName:
                    type: string
                  status:
                    type: string
                required:
                - priority
                type: object
              type: object
          required:
          - nodes
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
