apiVersion: postgresql.openshift.io/v1
kind: PostgreSQL
metadata:
  name: postgresql-cluster
spec:
  managementState: managed
  nodes:
    node-one:
      image: mcyprian/postgresql-10-fedora29
      priority: 100
      resources:
        limits:
          memory: 500Mi
          cpu: 200m
        requests:
          memory: 256Mi
          cpu: 100m
      storage:
        storageClassName: local-storage
        size: 256Mi
    node-two:
      image: mcyprian/postgresql-10-fedora29
      priority: 60
      resources:
        limits:
          memory: 500Mi
          cpu: 200m
        requests:
          memory: 256Mi
          cpu: 100m
      storage:
        storageClassName: local-storage
        size: 256Mi
    node-extra:
      image: mcyprian/postgresql-10-fedora29
      priority: 0
      resources:
        limits:
          memory: 500Mi
          cpu: 200m
        requests:
          memory: 256Mi
          cpu: 100m
      storage:
        storageClassName: local-storage
        size: 256Mi
      storage:
        storageClassName: local-storage
        size: 256Mi
